name: Deploy Databricks Bundle PRD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

      - name: Instalar uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash

<<<<<<< HEAD

      - name: Configurar credenciais Databricks (OAuth Service Principal)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PRD }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID_PRD }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_PRD }}
=======
      - name: Configurar credenciais Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PRD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PRD }}
>>>>>>> dev
        run: |
          mkdir -p ~/.databricks
          echo "[PRD]" > ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
<<<<<<< HEAD
          echo "client_id = $DATABRICKS_CLIENT_ID" >> ~/.databrickscfg
          echo "client_secret = $DATABRICKS_CLIENT_SECRET" >> ~/.databrickscfg
=======
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
>>>>>>> dev

      - name: Deploy bundle em PRD
        env:
          DATABRICKS_CONFIG_PROFILE: PRD
        run: |
          cd blip_dab_treinamento
          databricks bundle validate --target prd
          databricks bundle deploy --target prd
          databricks bundle run blip_dab_treinamento_job --target prd
